create database BALAJI_FAST_FOOD
 
 --SHOW ALL 
 SELECT * FROM [Balaji Fast Food Sales];

 -- DISPLAY ONLY ITEM_NAME,ITEM_PRIOCE,AND QUANTITY
 SELECT ITEM_NAME,ITEM_PRICE,QUANTITY FROM [Balaji Fast Food Sales];

 --SHOW ALL TRANSACTION WHERE TRANSACTION_TYPE = CASH 
 SELECT * FROM [Balaji Fast Food Sales] WHERE transaction_type='CASH';

 --SHOW ALL ORDERS MADE IN MORNING
 SELECT * FROM [Balaji Fast Food Sales] WHERE time_of_sale='MORNING';

 --FIND ALL TRNASACTION WHERE ITEM_TYPE=BEVERAGES
 SELECT * FROM [Balaji Fast Food Sales] WHERE ITEM_TYPE='BEVERAGES';

 --SHOW ORDERS WHERE QUANTITY IS MORE THE 5
 SELECT * FROM [Balaji Fast Food Sales] WHERE quantity >5;

 --DISPLAY ALL RECORDS SORTED BY DATE
 SELECT * FROM [Balaji Fast Food Sales] ORDER BY DATE ASC;

 --FIND TRANSACTION WHERE TRANSACTION_TYPE IS NULL
 SELECT * FROM [Balaji Fast Food Sales] WHERE transaction_type=NULL;

 --SHOW ALL ORDERS BETWEEN 2022-04-01 AND 2022-04-30
 SELECT * FROM [Balaji Fast Food Sales] WHERE DATE BETWEEN '2022-04-01' AND '2022-04-30';

 --FIND ALL ORDERS FOR THE ITEM VADAPAV
 SELECT * FROM [Balaji Fast Food Sales] WHERE ITEM_NAME ='VADAPAV';

 --FIND THE TOTAL SALES AMOUNT
 SELECT SUM(TRANSACTION_AMOUNT)  AS TOTAL_SALES FROM [Balaji Fast Food Sales];

 --FIND TOTAL SALES PER ITEM_NAME
 SELECT ITEM_NAME,SUM(TRANSACTION_AMOUNT) AS TOTAL_SALES FROM [Balaji Fast Food Sales] GROUP BY ITEM_NAME;

 --COUNT TOTAL NUMBER OF ORDERS
 SELECT COUNT(QUANTITY) AS TOTAL_NUMBER_OF_ITEMS FROM [Balaji Fast Food Sales];

 --FIND TOTAL QUANTITY SOLD PER ITEM 
 SELECT ITEM_NAME,COUNT(QUANTITY) AS TOTAL_QUANTITY_SOLD_PER_ITEM FROM [Balaji Fast Food Sales] GROUP BY ITEM_NAME;

 --FIND AVERAGE TRANSACTION AMOUNT
 SELECT AVG(TRANSACTION_AMOUNT) AS AVG_TRANSACTION_AMOUNT FROM [Balaji Fast Food Sales];

 --FIND TOTAL SALES PER TRANSACTION_TYPE 
 SELECT TRANSACTION_TYPE,SUM(TRANSACTION_AMOUNT) AS TOTAL_SALES FROM [Balaji Fast Food Sales] GROUP BY transaction_type;

 --FIND TOTAL SALES PER TIME_OF_SALES
 SELECT TIME_OF_SALE,SUM(TRANSACTION_AMOUNT) AS TOTAL_SALES FROM [Balaji Fast Food Sales] GROUP BY time_of_sale;

 --FIND THE MOST SOLD ITEM BY QUANTITY
 SELECT TOP 1 ITEM_NAME, SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD FROM [Balaji Fast Food Sales] GROUP BY ITEM_NAME 
 ORDER BY TOTAL_QUANTITY_SOLD DESC;

 --FIND THE MOST EXPENSIVE ITEM 
 SELECT TOP 1 ITEM_NAME ,SUM(ITEM_PRICE) AS MOST_EXPENSIVE FROM [Balaji Fast Food Sales] GROUP BY item_name
 ORDER BY MOST_EXPENSIVE DESC;

 --FIND TOTAL REVENUE PER DAY
 SELECT DATE,SUM(TRANSACTION_AMOUNT) AS TOTAL_REVENUE_PER_DAY FROM [Balaji Fast Food Sales] GROUP BY DATE ORDER BY DATE ASC;

 --FIND ITEMS WITH TOTAL SALES GREATER THANM 25000
 SELECT ITEM_NAME,SUM(TRANSACTION_AMOUNT) AS TOTAL_SALES FROM [Balaji Fast Food Sales] GROUP BY item_name
 HAVING SUM(TRANSACTION_AMOUNT)>25000;

 --FIND TOP 3 HIGEST REVENUE GENERATING ITEMS
 SELECT TOP 3 ITEM_NAME,SUM(TRANSACTION_AMOUNT) AS HIGEST_REVENUE_GENERATING_ITEMS FROM [Balaji Fast Food Sales] GROUP BY item_name;

 --FIND THE DAY WITH HIGHEST TOTAL SALES
 SELECT TOP 1 DATE,SUM(TRANSACTION_AMOUNT) AS HIGHEST_TOTAL_SALES FROM [Balaji Fast Food Sales] GROUP BY DATE
 ORDER BY DATE;

-RANK ITEM BASED ON TOTAL REVENUE
 SELECT ITEM_NAME,
 SUM(TRANSACTION_AMOUNT) AS TOTAL_REVENUE,
 RANK()OVER(ORDER BY SUM(TRANSACTION_AMOUNT)
 DESC) AS REVNUE_RANK 
 FROM [Balaji Fast Food Sales]
 GROUP BY item_name;

 --PERCENTAGE C ONTRIBUTION OF EACH IOTEM TO TOTAL REVENUE
 SELECT ITEM_NAME,
 SUM(TRANSACTION_AMOUNT) AS ITEM_REVENUE,
 ROUND(
   (SUM(TRANSACTION_AMOUNT)*100)/
   SUM(SUM(TRANSACTION_AMOUNT))OVER(),
 2
 )AS REVENUE_PERCENTAGE
 FROM [Balaji Fast Food Sales]
 GROUP BY ITEM_NAME;

--COMPARE CASH VS ONLINE SALES
SELECT
    SUM(CASE WHEN transaction_type = 'Cash'
             THEN transaction_amount ELSE 0 END) AS cash_revenue,
    SUM(CASE WHEN transaction_type = 'Online'
             THEN transaction_amount ELSE 0 END) AS online_revenue,
    SUM(CASE WHEN transaction_type = 'Cash'
             THEN transaction_amount ELSE 0 END)
    -
    SUM(CASE WHEN transaction_type = 'Online'
             THEN transaction_amount ELSE 0 END) AS revenue_difference
FROM [Balaji Fast Food Sales];

--GENERATE HIGHEST REVENUE WITH TIME OF SALES
SELECT TOP 1 TIME_OF_SALE ,
SUM(TRANSACTION_AMOUNT)AS TOTAL_REVENUE
FROM [Balaji Fast Food Sales]
GROUP BY time_of_sale
ORDER BY TOTAL_REVENUE;

--FIND REPEAT ITEM SOLD ON THE SAME DATE
SELECT DATE,ITEM_NAME,COUNT(*) AS TIME_SOLD
FROM [Balaji Fast Food Sales]
GROUP BY DATE,ITEM_NAME 
HAVING COUNT (*)>1
ORDER BY DATE DESC;

--SELECT TOP 2 CONTRIBUTION PERCENTAGE 
 SELECT TOP 2 ITEM_NAME,
 SUM(TRANSACTION_AMOUNT) AS ITEM_REVENUE,
 ROUND(
   (SUM(TRANSACTION_AMOUNT)*100)/
   SUM(SUM(TRANSACTION_AMOUNT))OVER(),
 2
 )AS REVENUE_PERCENTAGE
 FROM [Balaji Fast Food Sales]
 GROUP BY ITEM_NAME;

 --WHICH ITEMS MAKE THE MOST MONEY?
 SELECT TOP 1 ITEM_NAME,SUM(TRANSACTION_AMOUNT) AS TOTAL_REVENUE FROM [Balaji Fast Food Sales] GROUP BY ITEM_NAME;

 --WHICH TIME OF THE DAY HAS THE HIGHEST SALES 
 SELECT TOP 1 TIME_OF_SALE,SUM(TRANSACTION_AMOUNT) AS HIGEST_SALES FROM [Balaji Fast Food Sales] GROUP BY time_of_sale;

 --WHICH IS THE least PROFITABLE CATEGORY
 SELECT TOP 1 ITEM_TYPE,SUM(TRANSACTION_amount) as most_profitable_category from [Balaji Fast Food Sales] group by item_type 



